### ISSUE TITLE
Failed to find module: "nativescript-svg' @1.3.4

### ISSUE THREAD

**Issue by Hesamp** [peoplewareDo/nativescript-svg#22]
i run nativescript-svg in my project bun not fount module ; 
and try to run demo project But that did not answer;
What should I do? 
`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo3/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-svg", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-svg", relative to: app/tns_modules/
	at com.tns.Module.resolvePathHelper(Module.java:146)
	at com.tns.Module.resolvePath(Module.java:55)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
	at com.tns.Runtime.callJSMethod(Runtime.java:890)
	at com.tns.Runtime.callJSMethod(Runtime.java:874)
	at com.tns.Runtime.callJSMethod(Runtime.java:866)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
`

**Comment by sebastian-man** [comment]
I get the same error with the demo code:

```
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:3053:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: SVGImage.Error: Could not find module '../'. Computed path '/Users/****/Library/Developer/CoreSimulator/Devices/**/data/Containers/Bundle/Application/***/demoangular.app/app/tns_modules/nativescript-svg'.
```

**Comment by PeterStaev** [comment]
This is because the NPM package was not published correctly and contains TS files instead of JS files. Also this probably is the same as #23 .

**Comment by aMarCruz** [comment]
In its actual form, the npm package is unusable :-1:

**Comment by sean-perkins** [comment]
<img width="577" alt="screen shot 2017-08-02 at 11 59 09 am" src="https://user-images.githubusercontent.com/13732623/28882719-1499a126-777a-11e7-8611-8e4585ca7d2d.png">

I can confirm it's a problem with just the published NPM package. Created a fork and was able to manipulate it to render a SVG.

https://github.com/TeamMaestro/nativescript-svg

**Comment by dvdbrk** [comment]
@sean-perkins I still can't get it to work - any help would be appreciated.

**Comment by dvdbrk** [comment]
This is just painful. I thought I got it to work somehow yesterday, but today it doesnt't. Does anyone have it working, and which versions of everything works?

**Comment by G3N7** [comment]
any word on when this will be available again?

**Comment by sean-perkins** [comment]
☝️ to my original comment. There's a demonstration of how you can manage it in your own published npm package for now. 

```
"@teammaestro/nativescript-svg": "0.0.1"
```

We did it - wouldn't recommend as a long term solution.

**Comment by sebastian-man** [comment]
@sean-perkins 
Thx for sharing this. Can you please make a pull request for this fix?

**Comment by dvdbrk** [comment]
@sean-perkins I have tried to use your fork, but still fails silently. I am using latest NS and Angular versions, any ideas what am I doing wrong?

Also after cloning your fork, running `npm install` from withing demo-angular folder, followed by `tns run android`, gives me `app/app.module.ts(7,39): error TS2307: Cannot find module 'nativescript-svg/angular'.`

**Comment by sean-perkins** [comment]
@dvdbrk The import statement you showed is not accurate to the published package.

```
registerElement('SVGImage', () => require('@teammaestro/nativescript-svg').SVGImage);
```

**Comment by dvdbrk** [comment]
Yes, sorry - tried that as well 😢

**Comment by zoitsa** [comment]
Is there an update on this issue yet?

**Comment by dhagej** [comment]
Seems like this issue is forgotten 😟 . I'll try to use previous versions of this module today and see if any of them work correctly without giving this error.

**Comment by codmajik** [comment]
From native-script slack:
It seems the problem is that there are not compiled versions (.js) in the plugin. NS3 does not compile  plugin ts file on build so the plugin provider must provide a precompile js file.

This is some kind of optimization to prevent compiling large plugins there are not even being used.
