### ISSUE TITLE
TypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/

### ISSUE THREAD

**Issue by lucianohoffmann** [peoplewareDo/nativescript-svg#23]
Hi, I tested demo-angular and it runs but the svg is not showed. The console shows this message:

`TypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/`

**Comment by dvdbrk** [comment]
For me it fails silently

**Comment by amizz** [comment]
Having the same problem. Any solution?

**Comment by tontojones** [comment]
Same prob. Anyone? Bueller? Anyone?

Serially, I get the:

ypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to...

...not the silent failure

**Comment by noomieware** [comment]
I kept getting the error from above. Decided to skip the prepared android module and reregistered the element myself for use in angular:

`registerElement("Svg", () => require("nativescript-svg").ImageSourceSVG);`

Error changed slightly to 

`Failed to find module: "nativescript-svg", relative to: app/tns_modules/`


Here is a full stack trace from the error. 
Weird: If I check the generated apk, the folder nativescript-svg is in app/tns_modules.

[-1505459970995.txt](https://github.com/peoplewareDo/nativescript-svg/files/1305636/-1505459970995.txt)

**Comment by vultix** [comment]
I'm having this same error:
`Could not load view for: SVGImage.Error: Could not find module '../'.`
Has anyone found a solution?

**Comment by fthuin** [comment]
Experiencing the same error, here is the full error stack

```
JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.runScript(Native Method)
JS:     com.tns.Runtime.access$2200(Runtime.java:34)
JS:     com.tns.Runtime$2.run(Runtime.java:551)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6682)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
JS: TypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.runScript(Native Method)
JS:     com.tns.Runtime.access$2200(Runtime.java:34)
JS:     com.tns.Runtime$2.run(Runtime.java:551)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6682)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
JS:     at Object.getViewClass (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/nativescript-angular/element-registry.js:88:15)
JS:     at ViewUtil.createView (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/nativescript-angular/view-util.js:201:44)
JS:     at NativeScriptRenderer.createElement (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/nativescript-angular/renderer.js:109:30)
JS:     at DebugRenderer2.createElement (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:15198:49)
JS:     at createElement (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:10571:27)
JS:     at createViewNodes (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:13736:61)
JS:     at callViewAction (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:14209:13)
JS:     at execComponentViewsAction (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:14118:13)
JS:     at createViewNodes (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:13803:5)
JS:     at createRootView (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:13664:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:15089:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:14372:12)
JS:     at ComponentFactory_.create (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:11269:46)
JS:     at ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:4057:29)
JS:     at ViewContainerRef_.createComponent (file:///data/data/org.nativescript.tabacstopnativescript/files/app/tns_modules/@angular/core/bundles/co
JS: re.umd.js:11466:62)
```

**Comment by ramtinsoltani** [comment]
Same here, I used the demo-angular example and got this:
`TypeError: Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/`

**Comment by 1andee** [comment]
+1

**Comment by marklanhamhc** [comment]
+1
