### ISSUE TITLE
missing angular TS files in npm package

### ISSUE THREAD

**Issue by osmbsrn** [peoplewareDo/nativescript-svg#29]
Angular SVGDirective not working when using with typescript. Because the files below is not available in npm package. When I copy these files from GIT project, Angular directive works fine. Can you please add these TS files to npm package?

- nativescript-svg-directives.ts
- nativescript-svg-module.ts

**Comment by victorsosa** [comment]
fix on release 1.3.5

**Comment by gogoout** [comment]
I'm having this error when compiling. 
```
ERROR in ../node_modules/nativescript-svg/angular/nativescript-svg-module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/nativescript-svg/angular/nativescript-svg-module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:740:23)
    at plugin.done.then (.../node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ../node_modules/nativescript-svg/angular/index.ts 6:9-45
```

**Comment by victorsosa** [comment]
Doing another build to include the .TS files

**Comment by victorsosa** [comment]
try again with build 1.3.6

**Comment by victorsosa** [comment]
Ohh got you now, 

> remove all the *.ts(not *.d.ts) file in the npm package and it works.

I have to fine out how to filter the .ts file and not include in the filter the .d.ts files

**Comment by victorsosa** [comment]
please check out this package and confirm is the right one:

```
[vns@betito src]$ npm pack
npm notice 
npm notice 📦  nativescript-svg@1.3.7
npm notice === Tarball Contents === 
npm notice 1.7kB   package.json                                                                   
npm notice 140.9kB nativescript-svg-1.3.6.tgz                                                     
npm notice 154B    references.d.ts                                                                
npm notice 5.4kB   svg.android.js                                                                 
npm notice 5.6kB   svg.common.js                                                                  
npm notice 6.5kB   svg.d.ts                                                                       
npm notice 8.4kB   svg.ios.js                                                                     
npm notice 474B    tsconfig.json                                                                  
npm notice 43B     angular/index.d.ts                                                             
npm notice 222B    angular/index.js                                                               
npm notice 123B    angular/nativescript-svg-directives.d.ts                                       
npm notice 456B    angular/nativescript-svg-directives.js                                         
npm notice 47B     angular/nativescript-svg-module.d.ts                                           
npm notice 793B    angular/nativescript-svg-module.js                                             
npm notice 58B     angular/package.json                                                           
npm notice 72B     hooks/before-livesync/nativescript-angular-sync.js                             
npm notice 286B    platforms/android/include.gradle                                               
npm notice 13.9kB  platforms/android/libs/svg-android.jar                                         
npm notice 1.3kB   platforms/android/src/main/AndroidManifest.xml                                 
npm notice 1.3kB   platforms/android/src/main/assets/app/App_Resources/Android/AndroidManifest.xml
npm notice 34B     platforms/ios/build.xcconfig                                                   
npm notice 199B    platforms/ios/Podfile                                                          
npm notice === Tarball Details === 
npm notice name:          nativescript-svg                        
npm notice version:       1.3.7                                   
npm notice filename:      nativescript-svg-1.3.7.tgz              
npm notice package size:  162.2 kB                                
npm notice unpacked size: 187.7 kB                                
npm notice shasum:        d12ea3b6e3dee2ba283cad259687390b346cffa2
npm notice integrity:     sha512-QcBUBTPpcsFlC[...]lQYOyLTfCMz/Q==
npm notice total files:   22                                      
npm notice 
nativescript-svg-1.3.7.tgz
```

After you confirm it; I will publish the package 1.3.7

**Comment by victorsosa** [comment]
the issue was that the npmignore file wasn't in the right place

**Comment by gogoout** [comment]
Seems all correct now. Cheers.

**Comment by victorsosa** [comment]
Let me puplish and let me know

**Comment by victorsosa** [comment]
published

**Comment by gogoout** [comment]
Confirmed. Thanks.
